---

- hosts: saintjohnsnetwork
  become: true
  tasks:

  - name: Clean up apt cache
    apt:      
      autoremove: yes
      autoclean: yes
      update_cache: yes
    when: ansible_distribution in ["PureOS", "Ubuntu", "Debian"]
