---

- hosts: all
  become: true
  tasks:

  - name: Install alien, espeak, openssh-server and git
    package:
       name:
         - alien
         - espeak
         - openssh-server
         - git
       state: latest
       update_cache: yes
    when: ansible_distribution in ["PureOS", "Ubuntu", "Debian"]