---

- hosts: all
  become: true
  tasks:

  - name: Post Ubuntu installation packages
    package:
       name:
         - alien
         - espeak
         - openssh-server
         - git
         - tilix
         - xscreensaver
         - xscreensaver-gl
         - xscreensaver-gl-extra
         - tree
         - htop
         - gcc
         - shc
       state: latest
       update_cache: yes
    when: ansible_distribution in ["Ubuntu"]
