---

- hosts: saintjohnsnetwork
  become: true
  tasks:

  - name: Install updates
    apt:
       update_only: yes
       update_cache: yes
    when: ansible_distribution in ["ClearLinux"]

- hosts: distro_pureos
  become: true
  tasks:

  - name: Preferred packages
    package:
       name:
         - alien
         - espeak
         - openssh-server
         - git
         - tilix
         - xscreensaver
         - xscreensaver-gl
         - xscreensaver-gl-extra
       state: latest
    when: ansible_distribution == "ClearLinux"