---

- hosts: sjh
  become: true
  tasks:

  - name: Upgrading system release
    package:
      name: "*"
      command: default_release
    when: ansible_distribution in ["ClearLinux","Ubuntu"]

  - name: Post release upgrade update
    package:
      name: "*"
      force_apt_get: true
      state: latest
    when: ansible_distribution in ["ClearLinux","Ubuntu"]
