---

- hosts: sjh
  become: true
  tasks:

  - name: Update system repository index
    package:
      update_cache: yes
    when: ansible_distribution in ["ClearLinux","Ubuntu"]

  - name: Upgrade packages
    package:
      name: "*"
      force_apt_get: true
      state: latest
    when: ansible_distribution in ["ClearLinux","Ubuntu"]
