---

- hosts: lords_system
  become: true
  tasks:

  - name: Update system repository index
    apt:
      name: "*"
      update_cache: yes
      state: latest
    when: ansible_distribution in ["Ubuntu"]
